import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useAuth } from "@/lib/auth";
import { generatedAssetsQuery } from "@/lib/queries";
import { FolderOpen, Rocket, FileText, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/app/assets")({ component: AssetsPage });

function AssetsPage() {
  const { currentOrgId } = useAuth();
  const assetsQ = useQuery({ ...generatedAssetsQuery(currentOrgId ?? ""), enabled: !!currentOrgId });
  const assets = assetsQ.data ?? [];

  return (
    <div className="space-y-6">
      <div>
        <div className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">Library</div>
        <h1 className="mt-1 font-display text-2xl font-semibold tracking-tight">Assets</h1>
        <p className="mt-1 text-sm text-muted-foreground">Everything generated by your AI tools, in one place.</p>
      </div>

      {assets.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary">
            <FolderOpen className="h-6 w-6" />
          </div>
          <h2 className="mt-4 font-display text-lg font-semibold">No assets yet</h2>
          <p className="mt-1 text-sm text-muted-foreground">Run a tool in Launchpad and save the output to your library.</p>
          <Link to="/app/launchpad"><Button className="mt-4 gap-2"><Rocket className="h-4 w-4" /> Open Launchpad</Button></Link>
        </div>
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {assets.map((a) => (
            <div key={a.id} className="group rounded-2xl border border-border bg-card p-5 transition hover:border-primary/40 hover:shadow-elevated">
              <div className="flex items-start justify-between gap-2">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <FileText className="h-4.5 w-4.5" />
                </div>
                <span className="rounded-full border border-border bg-background/60 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                  {a.kind ?? a.category}
                </span>
              </div>
              <div className="mt-3 truncate text-sm font-medium">{a.title}</div>
              <div className="mt-1 text-[11px] text-muted-foreground">{new Date(a.created_at).toLocaleDateString()}</div>
              <div className="mt-4 flex gap-2">
                <Button size="sm" variant="outline" className="flex-1 gap-1.5"><Download className="h-3.5 w-3.5" /> Download</Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
